---
title: "Group 1"
author: "Hannah Lee"
date: '2022-11-22'
output: html_document
---

```{r}
library(tidyverse)
library(plotly)
library(broom)
suppressPackageStartupMessages(library(tidyverse))
suppressPackageStartupMessages(library(broom))
suppressPackageStartupMessages(library(modelr))
score <- read.csv("exams.csv")
```
# wrangling

```{r}
exam_df <-
  score %>%
  mutate(eng.score = (reading.score + writing.score)/2) %>%
  select(c(6, 9))
```
# summerize
```{r}
exam_df %>%
  summarize(
     eng_mean = mean(eng.score),
     eng_median = median(eng.score),
     eng_standard_deviation = sd(eng.score),
     eng_minimum = min(eng.score),
     eng_maximum = max(eng.score)
  )
```




# lm


```{r}
exam_model <- lm( math.score ~ eng.score, exam_df)
```

```{r}
exam_model %>%
tidy()
```

```{r}
exam_model %>%
  glance() %>%
  select(1:3)
```

```{r}
exam_new <- exam_df %>%
  add_predictions(exam_model) %>%
  add_residuals(exam_model)
```



```{r}
ggplot(exam_df) +
  geom_point(mapping = aes(x = eng.score, y = math.score)) +
  geom_abline(slope = exam_model$coefficients[2],
              intercept = exam_model$coefficients[1]	) +
   labs(
  title = "Relationships with math score and english score",
  y = "math score", x = "english score"
)
```
# 3 assumptions
```{r}
exam_new %>%
  ggplot() +
  geom_histogram(mapping = aes(x = resid), color = "darkblue", fill = "lightblue",  binwidth = 3.9) +
   labs(
  title = "Examination of the risiduals of exam_df",
  y = "count", x = "residual")

```
